---
- hosts: all
  tasks:

  - name: Update apt with the latest packages
    apt: update_cache=yes

  - name: Install Apache2
    apt: pkg=apache2 state=present

  - name: Install libapache2-mod-php5
    apt: pkg=libapache2-mod-php5 state=present

  - name: Install PHP5
    apt: pkg=php5 state=present

  - name: Install PHP modules
    apt: name={{ item }} state=installed
    with_items:
       - php5-mysql
       - php5-curl
       - php5-gd
       - php5-intl
       - php-pear
       - php5-imap
       - php5-mcrypt
       - php5-ming
       - php5-ps
       - php5-pspell
       - php5-recode
       - php5-snmp
       - php5-sqlite
       - php5-tidy
       - php5-xmlrpc
       - php5-xsl
       - php-apc

  - name: Clear /var/www so we can replace it with a symlink to a directory shared with the host
    file: path=/var/www state=absent

  - name: Make sure the httpdocs shared directory exists
    file: path=/vagrant/httpdocs state=directory

  - name: Symlink the shared directory to the web root on the VM
    file: src=/vagrant/httpdocs dest=/var/www state=link

  - name: Replace contents of default Apache vhost
    template: src=default.vhost.j2 dest=/etc/apache2/sites-enabled/000-default

  - name: Enable Apache rewrite module
    command: a2enmod rewrite

  - name: Restart Apache
    service: name=apache2 state=restarted

  - name: Install MySQL
    apt: pkg=mysql-server-5.5 state=present

  - name: Install python-mysqldb
    apt: pkg=python-mysqldb state=present

  - name: Setup magentodb
    mysql_db: name=magentodb state=present

  - name: create magentodb user and grant access to the db
    mysql_user: name=magentouser host=localhost password=password priv=magentodb.*:ALL state=present


  # Magento
  # --------------------
  # http://www.magentocommerce.com/wiki/1_-_installation_and_configuration/installing_magento_via_shell_ssh

  # TODO Only run this block if we haven't already downloaded Magento
  # if [ ! -f "/vagrant/httpdocs/index.php" ]; then
  - name: Download Magento
    get_url: url=http://www.magentocommerce.com/downloads/assets/1.8.1.0/magento-1.8.1.0.tar.gz dest=/vagrant/httpdocs/magento-1.8.1.0.tar.gz 

  - name: Extract Magento
    command: tar -zxvf magento-1.8.1.0.tar.gz --strip-components 1 chdir=/vagrant/httpdocs/

  - name: Set Permisisons on media and var
    command: chmod -R o+w media var chdir=/vagrant/httpdocs/

  - name: Set Permissions on app/etc
    command: chmod o+w app/etc chdir=/vagrant/httpdocs/

  - name: Clean up downloaded file
    file: path=/vagrant/httpdocs/magento-1.8.1.0.tar.gz state=absent
  # fi

  - name: Run the Magento Installer
    command: sudo /usr/bin/php -f install.php -- --license_agreement_accepted yes --locale en_US --timezone "America/Los_Angeles" --default_currency USD --db_host localhost --db_name magentodb --db_user magentouser --db_pass password --url "http://127.0.0.1:8080/" --use_rewrites yes --use_secure no --secure_base_url "http://127.0.0.1:8080/" --use_secure_admin no --skip_url_validation yes --admin_lastname Owner --admin_firstname Store --admin_email "admin@example.com" --admin_username admin --admin_password password123123 chdir=/vagrant/httpdocs creates=/vagrant/httpdocs/app/etc/local.xml    

  - name: Download netz98 magerun CLI tools
    get_url: url=https://raw.github.com/netz98/n98-magerun/master/n98-magerun.phar dest=/usr/local/bin/